name: flutter_riverpod_state_management_complete
description: Flutter Project to Discover Complete Riverpod State Management in Flutter.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
flutter_icons:
  image_path: "assets/images/riverpod_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/

